"""
Vocab sub-app content library.

Kept separate from `routes/vocab.py` so the API layer stays focused on request
handling. All lists here are the source of truth for the idempotent seed on
startup — add entries freely; existing progress rows keyed by word/lesson id
are untouched by re-seeding.
"""

from __future__ import annotations

from typing import Any


TOPICS_SEED: list[dict[str, Any]] = [
    # ── Healthcare cluster ─────────────────────────────────────────────
    {"id": "medicine", "name": "Medicine", "subtitle": "For healthcare providers", "icon": "medical-outline", "color": "lime"},
    {"id": "virology", "name": "Virology", "subtitle": "Viruses & immunology", "icon": "nutrition-outline", "color": "mint"},
    {"id": "pharmacy", "name": "Pharmacy", "subtitle": "Medicines & prescriptions", "icon": "medkit-outline", "color": "purple"},
    {"id": "genetics", "name": "Genetics", "subtitle": "DNA & heredity", "icon": "git-branch-outline", "color": "mint"},
    {"id": "anatomy", "name": "Anatomy", "subtitle": "Body systems", "icon": "body-outline", "color": "purple"},
    {"id": "nursing", "name": "Nursing", "subtitle": "Bedside care & procedures", "icon": "heart-circle-outline", "color": "mint"},
    {"id": "mental-health", "name": "Mental Health", "subtitle": "Psychology & wellbeing", "icon": "happy-outline", "color": "purple"},

    # ── Academic & professional ───────────────────────────────────────
    {"id": "education", "name": "Education", "subtitle": "For education professionals", "icon": "school-outline", "color": "lime"},
    {"id": "business", "name": "Business", "subtitle": "For career development", "icon": "briefcase-outline", "color": "lime"},
    {"id": "finance", "name": "Finance", "subtitle": "Money, banking & markets", "icon": "cash-outline", "color": "mint"},
    {"id": "law", "name": "Law", "subtitle": "Legal terms & practice", "icon": "shield-checkmark-outline", "color": "purple"},
    {"id": "science", "name": "Science", "subtitle": "For university students", "icon": "flask-outline", "color": "lime"},
    {"id": "tech", "name": "Tech", "subtitle": "For software engineers", "icon": "code-slash-outline", "color": "purple"},
    {"id": "marketing", "name": "Marketing", "subtitle": "Brands, ads & growth", "icon": "megaphone-outline", "color": "lime"},

    # ── Lifestyle & culture ───────────────────────────────────────────
    {"id": "travel", "name": "Travel", "subtitle": "For nomads & tourists", "icon": "airplane-outline", "color": "mint"},
    {"id": "cooking", "name": "Cooking", "subtitle": "Kitchen & cuisine", "icon": "restaurant-outline", "color": "lime"},
    {"id": "sports", "name": "Sports", "subtitle": "Fitness & competition", "icon": "football-outline", "color": "mint"},
    {"id": "music", "name": "Music", "subtitle": "Sound, rhythm & performance", "icon": "musical-notes-outline", "color": "purple"},
    {"id": "movies", "name": "Movies", "subtitle": "Cinema & storytelling", "icon": "film-outline", "color": "mint"},
    {"id": "fashion", "name": "Fashion", "subtitle": "Style & clothing", "icon": "shirt-outline", "color": "purple"},
    {"id": "art", "name": "Art", "subtitle": "Painting, design & craft", "icon": "color-palette-outline", "color": "lime"},
    {"id": "literature", "name": "Literature", "subtitle": "Books & storytelling", "icon": "book-outline", "color": "mint"},

    # ── Environment & society ─────────────────────────────────────────
    {"id": "environment", "name": "Environment", "subtitle": "Climate & sustainability", "icon": "leaf-outline", "color": "lime"},
    {"id": "nature", "name": "Nature", "subtitle": "Wildlife & landscapes", "icon": "flower-outline", "color": "mint"},
    {"id": "space", "name": "Space", "subtitle": "Astronomy & the cosmos", "icon": "planet-outline", "color": "purple"},
    {"id": "politics", "name": "Politics", "subtitle": "Government & policy", "icon": "flag-outline", "color": "mint"},
    {"id": "psychology", "name": "Psychology", "subtitle": "Mind & behaviour", "icon": "sparkles-outline", "color": "lime"},
]


WORDS_SEED: dict[str, list[dict[str, str]]] = {
    # ── Healthcare cluster ─────────────────────────────────────────────
    "medicine": [
        {"term": "Diagnosis", "translation": "identifying an illness", "example": "The doctor confirmed the diagnosis after several tests."},
        {"term": "Prognosis", "translation": "likely course of an illness", "example": "The prognosis is good with early treatment."},
        {"term": "Symptom", "translation": "physical or mental feature of illness", "example": "Fever is a common symptom of infection."},
        {"term": "Chronic", "translation": "long-lasting", "example": "She suffers from chronic back pain."},
        {"term": "Acute", "translation": "sudden and severe", "example": "He had an acute allergic reaction."},
        {"term": "Prescribe", "translation": "order medicine or treatment", "example": "The doctor prescribed antibiotics."},
        {"term": "Referral", "translation": "sending a patient to a specialist", "example": "I need a referral to see a cardiologist."},
        {"term": "Consent", "translation": "permission for treatment", "example": "The patient signed the consent form."},
        {"term": "Discharge", "translation": "release from hospital", "example": "She was discharged after two nights."},
        {"term": "Follow-up", "translation": "later check-in visit", "example": "Please book a follow-up in two weeks."},
        {"term": "Vital signs", "translation": "pulse, temperature, breathing", "example": "The nurse recorded his vital signs hourly."},
        {"term": "Allergy", "translation": "immune reaction to a substance", "example": "He has a peanut allergy."},
        {"term": "Screening", "translation": "test to catch disease early", "example": "Annual screening detects cancer sooner."},
        {"term": "Rehabilitation", "translation": "recovery therapy", "example": "Rehabilitation helped her walk again."},
    ],
    "virology": [
        {"term": "Pathogen", "translation": "disease-causing agent", "example": "Viruses are a common type of pathogen."},
        {"term": "Antibody", "translation": "immune protein", "example": "Antibodies help fight infection."},
        {"term": "Antigen", "translation": "molecule that triggers immunity", "example": "The antigen was identified quickly."},
        {"term": "Vaccine", "translation": "trains immunity", "example": "The vaccine reduces severe disease."},
        {"term": "Contagious", "translation": "easily spread", "example": "Measles is highly contagious."},
        {"term": "Quarantine", "translation": "isolation to prevent spread", "example": "He was placed in quarantine for 10 days."},
        {"term": "Outbreak", "translation": "sudden appearance of disease", "example": "There is a flu outbreak at the school."},
        {"term": "Incubation", "translation": "time before symptoms", "example": "The incubation period is 3–5 days."},
        {"term": "Immunity", "translation": "protection from disease", "example": "Vaccines build long-term immunity."},
        {"term": "Mutation", "translation": "genetic change", "example": "A new mutation increased transmissibility."},
        {"term": "Variant", "translation": "changed version of a virus", "example": "The variant spread across borders."},
        {"term": "Aerosol", "translation": "tiny airborne particles", "example": "The virus spreads through aerosols."},
    ],
    "pharmacy": [
        {"term": "Dosage", "translation": "amount of medicine", "example": "The dosage is one tablet twice a day."},
        {"term": "Side effect", "translation": "unwanted effect", "example": "Drowsiness is a common side effect."},
        {"term": "Refill", "translation": "renew a prescription", "example": "I need a refill for my medication."},
        {"term": "Over the counter", "translation": "no prescription needed", "example": "Ibuprofen is over the counter."},
        {"term": "Generic", "translation": "non-brand version", "example": "The generic works the same as the brand."},
        {"term": "Interaction", "translation": "one drug affecting another", "example": "Ask about drug interactions."},
        {"term": "Contraindication", "translation": "reason not to prescribe", "example": "Pregnancy is a contraindication."},
        {"term": "Sublingual", "translation": "under the tongue", "example": "Take the tablet sublingually."},
        {"term": "Topical", "translation": "applied to skin", "example": "Use the topical cream twice daily."},
        {"term": "Regimen", "translation": "planned schedule of treatment", "example": "Follow the full antibiotic regimen."},
        {"term": "Adherence", "translation": "sticking to the plan", "example": "Adherence improves outcomes."},
        {"term": "Pharmacist", "translation": "medicine expert", "example": "Ask your pharmacist about supplements."},
    ],
    "genetics": [
        {"term": "Gene", "translation": "unit of heredity", "example": "This gene affects eye color."},
        {"term": "DNA", "translation": "genetic material", "example": "DNA carries genetic information."},
        {"term": "Mutation", "translation": "change in DNA", "example": "A mutation can cause disease."},
        {"term": "Heredity", "translation": "passing traits from parents", "example": "Heredity shapes many traits."},
        {"term": "Allele", "translation": "gene variant", "example": "Each parent contributed one allele."},
        {"term": "Chromosome", "translation": "packaged DNA", "example": "Humans have 23 chromosome pairs."},
        {"term": "Genome", "translation": "complete set of genes", "example": "The human genome was sequenced in 2003."},
        {"term": "Trait", "translation": "observable feature", "example": "Eye color is a genetic trait."},
        {"term": "Dominant", "translation": "expressed when present", "example": "Brown eyes are dominant."},
        {"term": "Recessive", "translation": "needs two copies to appear", "example": "Blue eyes are recessive."},
        {"term": "Inheritance", "translation": "how traits pass down", "example": "Study the inheritance pattern."},
        {"term": "Genotype", "translation": "genetic makeup", "example": "Her genotype was analysed."},
    ],
    "anatomy": [
        {"term": "Cardiac", "translation": "relating to the heart", "example": "Cardiac arrest is a medical emergency."},
        {"term": "Pulmonary", "translation": "relating to the lungs", "example": "Pulmonary function was normal."},
        {"term": "Vascular", "translation": "relating to blood vessels", "example": "Vascular disease can be prevented."},
        {"term": "Neural", "translation": "relating to nerves", "example": "Neural pathways carry signals."},
        {"term": "Cranial", "translation": "of the skull", "example": "The cranial nerves control the face."},
        {"term": "Skeletal", "translation": "of the bones", "example": "Skeletal muscles enable movement."},
        {"term": "Hepatic", "translation": "of the liver", "example": "Hepatic enzymes were elevated."},
        {"term": "Renal", "translation": "of the kidneys", "example": "Renal failure requires dialysis."},
        {"term": "Digestive", "translation": "processing food", "example": "The digestive tract is long."},
        {"term": "Endocrine", "translation": "hormone-producing", "example": "The endocrine system controls hormones."},
        {"term": "Lymphatic", "translation": "immune drainage", "example": "The lymphatic system filters toxins."},
        {"term": "Musculoskeletal", "translation": "muscles and bones together", "example": "Musculoskeletal pain is common."},
    ],
    "nursing": [
        {"term": "IV drip", "translation": "intravenous fluids", "example": "The IV drip is running slowly."},
        {"term": "Bedside manner", "translation": "how a caregiver interacts", "example": "Her bedside manner is warm."},
        {"term": "Shift", "translation": "scheduled work period", "example": "I work the night shift."},
        {"term": "Handover", "translation": "briefing at end of shift", "example": "The handover took 20 minutes."},
        {"term": "Vitals", "translation": "vital sign readings", "example": "Please check vitals every hour."},
        {"term": "Catheter", "translation": "thin tube inserted into body", "example": "The catheter was placed correctly."},
        {"term": "Sterile", "translation": "germ-free", "example": "Keep the field sterile."},
        {"term": "Wound care", "translation": "cleaning and dressing", "example": "Wound care prevents infection."},
        {"term": "Charting", "translation": "recording patient data", "example": "Charting takes an hour."},
        {"term": "Compassion", "translation": "kind concern for others", "example": "Nursing requires compassion."},
        {"term": "Assessment", "translation": "evaluating a patient", "example": "Complete a full assessment on arrival."},
        {"term": "Triage", "translation": "sorting by urgency", "example": "Triage the incoming patients."},
    ],
    "mental-health": [
        {"term": "Anxiety", "translation": "excessive worry", "example": "He copes well with anxiety."},
        {"term": "Depression", "translation": "persistent low mood", "example": "Therapy can help with depression."},
        {"term": "Resilience", "translation": "ability to recover", "example": "Resilience is a skill."},
        {"term": "Mindfulness", "translation": "focused awareness", "example": "Mindfulness reduces stress."},
        {"term": "Coping", "translation": "managing difficulty", "example": "Find healthy coping strategies."},
        {"term": "Therapy", "translation": "structured mental treatment", "example": "Weekly therapy sessions help."},
        {"term": "Trauma", "translation": "psychological injury", "example": "Trauma can echo for years."},
        {"term": "Burnout", "translation": "exhaustion from stress", "example": "Watch for signs of burnout."},
        {"term": "Support system", "translation": "people who help you", "example": "Build a strong support system."},
        {"term": "Wellbeing", "translation": "overall good state", "example": "Prioritise your wellbeing."},
        {"term": "Cognitive", "translation": "of thinking", "example": "Cognitive tools help reframe."},
        {"term": "Empathy", "translation": "understanding others' feelings", "example": "Empathy strengthens relationships."},
    ],

    # ── Academic & professional ───────────────────────────────────────
    "education": [
        {"term": "Curriculum", "translation": "planned learning content", "example": "The curriculum covers grammar and reading."},
        {"term": "Assessment", "translation": "evaluation of learning", "example": "Weekly assessments track progress."},
        {"term": "Feedback", "translation": "response to work", "example": "Constructive feedback improves writing."},
        {"term": "Pedagogy", "translation": "teaching methods", "example": "Modern pedagogy emphasises active learning."},
        {"term": "Rubric", "translation": "grading criteria", "example": "The rubric explains each grade."},
        {"term": "Scaffolding", "translation": "step-by-step support", "example": "Scaffolding builds confidence."},
        {"term": "Differentiation", "translation": "adapting to learners", "example": "Differentiation reaches every student."},
        {"term": "Engagement", "translation": "active involvement", "example": "Engagement drives outcomes."},
        {"term": "Assignment", "translation": "task to complete", "example": "Turn in the assignment on Friday."},
        {"term": "Retention", "translation": "keeping information", "example": "Spaced review improves retention."},
        {"term": "Outcomes", "translation": "goals of learning", "example": "Learning outcomes must be measurable."},
        {"term": "Enrolment", "translation": "signing up to a course", "example": "Enrolment closes Monday."},
    ],
    "business": [
        {"term": "Revenue", "translation": "income from sales", "example": "Revenue grew 20% last quarter."},
        {"term": "Stakeholder", "translation": "interested party", "example": "We updated all stakeholders on the launch."},
        {"term": "Deadline", "translation": "final date", "example": "The deadline is next Friday."},
        {"term": "Negotiate", "translation": "reach an agreement", "example": "They negotiated a better price."},
        {"term": "Pipeline", "translation": "potential deals in progress", "example": "Our pipeline is healthy this quarter."},
        {"term": "KPI", "translation": "key performance indicator", "example": "Track KPIs weekly."},
        {"term": "Escalate", "translation": "raise to higher level", "example": "Escalate to the director if blocked."},
        {"term": "Milestone", "translation": "important checkpoint", "example": "We hit the alpha milestone."},
        {"term": "Onboarding", "translation": "bringing in new members", "example": "Onboarding takes two weeks."},
        {"term": "Stakeout", "translation": "long-term forecast", "example": "The stakeout for Q4 looks solid."},
        {"term": "Synergy", "translation": "combined effect", "example": "The merger created strong synergy."},
        {"term": "Runway", "translation": "months of cash left", "example": "We have 12 months of runway."},
    ],
    "finance": [
        {"term": "Asset", "translation": "something owned of value", "example": "A house is a major asset."},
        {"term": "Liability", "translation": "money owed", "example": "Reduce liabilities to grow wealth."},
        {"term": "Equity", "translation": "owned share of value", "example": "You have 20% equity."},
        {"term": "Dividend", "translation": "profit paid to shareholders", "example": "The dividend was raised."},
        {"term": "Portfolio", "translation": "collection of investments", "example": "Diversify your portfolio."},
        {"term": "Volatility", "translation": "price fluctuation", "example": "Crypto has high volatility."},
        {"term": "Hedge", "translation": "protect against risk", "example": "Options are used to hedge."},
        {"term": "Yield", "translation": "return on investment", "example": "Bond yields are rising."},
        {"term": "Inflation", "translation": "prices going up", "example": "Inflation affects real returns."},
        {"term": "Recession", "translation": "economic downturn", "example": "A recession lasts months."},
        {"term": "Interest", "translation": "cost of borrowed money", "example": "Compound interest matters."},
        {"term": "Loan", "translation": "borrowed money", "example": "The loan was approved."},
    ],
    "law": [
        {"term": "Contract", "translation": "binding agreement", "example": "Sign the contract carefully."},
        {"term": "Plaintiff", "translation": "person who sues", "example": "The plaintiff filed today."},
        {"term": "Defendant", "translation": "person being sued", "example": "The defendant denies the claim."},
        {"term": "Verdict", "translation": "jury decision", "example": "The verdict was unanimous."},
        {"term": "Statute", "translation": "written law", "example": "That statute was updated."},
        {"term": "Liability", "translation": "legal responsibility", "example": "They assumed liability."},
        {"term": "Jurisdiction", "translation": "authority to rule", "example": "This court has jurisdiction."},
        {"term": "Appeal", "translation": "ask a higher court", "example": "They will appeal the ruling."},
        {"term": "Testimony", "translation": "witness statement", "example": "Her testimony was clear."},
        {"term": "Precedent", "translation": "prior guiding decision", "example": "The precedent stands."},
        {"term": "Bail", "translation": "money to be released", "example": "Bail was set at $10,000."},
        {"term": "Settlement", "translation": "agreed resolution", "example": "They reached a settlement."},
    ],
    "science": [
        {"term": "Hypothesis", "translation": "testable prediction", "example": "The hypothesis was confirmed."},
        {"term": "Experiment", "translation": "test to check a hypothesis", "example": "The experiment produced clear results."},
        {"term": "Data", "translation": "collected information", "example": "We analysed the data carefully."},
        {"term": "Variable", "translation": "factor that changes", "example": "Control one variable at a time."},
        {"term": "Control", "translation": "unchanged reference", "example": "The control group took placebo."},
        {"term": "Peer review", "translation": "expert check of research", "example": "The paper passed peer review."},
        {"term": "Correlation", "translation": "related change", "example": "Correlation does not imply causation."},
        {"term": "Causation", "translation": "cause-and-effect", "example": "Establishing causation is harder."},
        {"term": "Empirical", "translation": "based on observation", "example": "Show empirical evidence."},
        {"term": "Theory", "translation": "well-supported explanation", "example": "Evolution is a strong theory."},
        {"term": "Replication", "translation": "repeating a study", "example": "Replication builds trust."},
        {"term": "Sample", "translation": "subset studied", "example": "Use a larger sample size."},
    ],
    "tech": [
        {"term": "Bug", "translation": "programming error", "example": "I fixed a bug in the login flow."},
        {"term": "Deploy", "translation": "release software", "example": "We deploy every Thursday."},
        {"term": "Feature", "translation": "product capability", "example": "The new feature ships this week."},
        {"term": "Refactor", "translation": "restructure code", "example": "We refactored the auth module."},
        {"term": "Cache", "translation": "fast temporary storage", "example": "The cache reduced load time."},
        {"term": "API", "translation": "application programming interface", "example": "The API is documented."},
        {"term": "Framework", "translation": "reusable code foundation", "example": "React is a popular framework."},
        {"term": "Deployment", "translation": "release event", "example": "Deployment was smooth."},
        {"term": "Repository", "translation": "code storage", "example": "Push your branch to the repository."},
        {"term": "Endpoint", "translation": "API URL", "example": "That endpoint returns JSON."},
        {"term": "Payload", "translation": "data sent in a request", "example": "The payload is JSON."},
        {"term": "Latency", "translation": "response delay", "example": "Latency dropped after caching."},
        {"term": "Scalability", "translation": "ability to grow", "example": "Design for scalability."},
    ],
    "marketing": [
        {"term": "Funnel", "translation": "stages to conversion", "example": "Optimize the marketing funnel."},
        {"term": "Conversion", "translation": "desired action taken", "example": "The conversion rate improved."},
        {"term": "Retention", "translation": "keeping customers", "example": "Retention is cheaper than acquisition."},
        {"term": "Acquisition", "translation": "gaining new users", "example": "Paid ads drive acquisition."},
        {"term": "Segment", "translation": "targeted group", "example": "Segment by behaviour."},
        {"term": "A/B test", "translation": "compare two versions", "example": "Run an A/B test on the button."},
        {"term": "Impressions", "translation": "times shown", "example": "Impressions doubled this week."},
        {"term": "CTR", "translation": "click-through rate", "example": "The CTR climbed above 3%."},
        {"term": "Attribution", "translation": "crediting the touchpoint", "example": "Multi-touch attribution matters."},
        {"term": "Brand", "translation": "identity of a company", "example": "Their brand feels bold."},
        {"term": "Positioning", "translation": "market place in mind", "example": "Positioning defines the story."},
        {"term": "Persona", "translation": "target user profile", "example": "Build a buyer persona."},
    ],

    # ── Lifestyle & culture ───────────────────────────────────────────
    "travel": [
        {"term": "Itinerary", "translation": "travel plan", "example": "Here is our itinerary for the trip."},
        {"term": "Boarding pass", "translation": "pass to enter a plane", "example": "Please show your boarding pass."},
        {"term": "Layover", "translation": "stop between flights", "example": "We have a two-hour layover in Rome."},
        {"term": "Jet lag", "translation": "tiredness from time change", "example": "The jet lag lasted two days."},
        {"term": "Check-in", "translation": "register at hotel or airport", "example": "Check-in opens at three."},
        {"term": "Passport", "translation": "travel identity document", "example": "Renew your passport early."},
        {"term": "Visa", "translation": "permit to enter a country", "example": "Apply for a visa online."},
        {"term": "Customs", "translation": "border control", "example": "Declare items at customs."},
        {"term": "Souvenir", "translation": "keepsake from a trip", "example": "She bought a small souvenir."},
        {"term": "Currency", "translation": "money of a country", "example": "Exchange currency before you go."},
        {"term": "Reservation", "translation": "advance booking", "example": "Do you have a reservation?"},
        {"term": "Guided tour", "translation": "led group excursion", "example": "We took a guided tour."},
    ],
    "cooking": [
        {"term": "Simmer", "translation": "cook gently below boiling", "example": "Simmer the sauce for 20 minutes."},
        {"term": "Sauté", "translation": "cook quickly in fat", "example": "Sauté the onions until golden."},
        {"term": "Whisk", "translation": "beat with a wire tool", "example": "Whisk the eggs vigorously."},
        {"term": "Marinate", "translation": "soak in flavour", "example": "Marinate the chicken overnight."},
        {"term": "Season", "translation": "add salt and spices", "example": "Season generously with salt."},
        {"term": "Dice", "translation": "cut into small cubes", "example": "Dice the onion finely."},
        {"term": "Julienne", "translation": "cut into thin strips", "example": "Julienne the carrots."},
        {"term": "Preheat", "translation": "heat oven in advance", "example": "Preheat the oven to 200°C."},
        {"term": "Reduce", "translation": "thicken by boiling", "example": "Reduce the sauce by half."},
        {"term": "Baste", "translation": "spoon fat over meat", "example": "Baste the turkey often."},
        {"term": "Fold", "translation": "gently mix", "example": "Fold in the whipped cream."},
        {"term": "Al dente", "translation": "firm to bite", "example": "Cook pasta al dente."},
    ],
    "sports": [
        {"term": "Endurance", "translation": "long-lasting stamina", "example": "Long runs build endurance."},
        {"term": "Cardio", "translation": "heart exercise", "example": "Cardio boosts fitness."},
        {"term": "Strength", "translation": "muscle power", "example": "Strength training pays off."},
        {"term": "Warm-up", "translation": "gentle start", "example": "Always warm up first."},
        {"term": "Cool-down", "translation": "gentle finish", "example": "Cool-down helps recovery."},
        {"term": "Personal best", "translation": "your record", "example": "She hit a personal best."},
        {"term": "Overtime", "translation": "extra playing time", "example": "The game went into overtime."},
        {"term": "Injury", "translation": "harm to the body", "example": "Prevent injury with stretching."},
        {"term": "Coach", "translation": "trainer or leader", "example": "The coach gave a pep talk."},
        {"term": "Tactics", "translation": "planned strategies", "example": "Adjust your tactics."},
        {"term": "Formation", "translation": "player arrangement", "example": "They switched to a 4-3-3 formation."},
        {"term": "Substitute", "translation": "replacement player", "example": "Send in a substitute."},
    ],
    "music": [
        {"term": "Melody", "translation": "main tune", "example": "The melody is catchy."},
        {"term": "Harmony", "translation": "notes played together", "example": "Their harmony is beautiful."},
        {"term": "Rhythm", "translation": "pattern of beats", "example": "The rhythm made me dance."},
        {"term": "Tempo", "translation": "speed of music", "example": "Slow the tempo a bit."},
        {"term": "Chord", "translation": "notes struck together", "example": "Play a G chord."},
        {"term": "Scale", "translation": "sequence of notes", "example": "Practice the major scale."},
        {"term": "Genre", "translation": "style of music", "example": "Jazz is my favourite genre."},
        {"term": "Verse", "translation": "song section with lyrics", "example": "The verse tells the story."},
        {"term": "Chorus", "translation": "repeating hook", "example": "The chorus is unforgettable."},
        {"term": "Bridge", "translation": "contrasting section", "example": "The bridge changes the mood."},
        {"term": "Lyrics", "translation": "song words", "example": "The lyrics are poetic."},
        {"term": "Producer", "translation": "person who makes the track", "example": "The producer added strings."},
    ],
    "movies": [
        {"term": "Plot", "translation": "main story", "example": "The plot has surprising twists."},
        {"term": "Cast", "translation": "actors in the film", "example": "The cast is stellar."},
        {"term": "Director", "translation": "person leading the film", "example": "The director is famous."},
        {"term": "Screenplay", "translation": "film script", "example": "She wrote the screenplay."},
        {"term": "Sequel", "translation": "later film in a series", "example": "The sequel opens Friday."},
        {"term": "Prequel", "translation": "earlier story", "example": "The prequel explains everything."},
        {"term": "Cinematography", "translation": "art of filming", "example": "Beautiful cinematography."},
        {"term": "Soundtrack", "translation": "music of the film", "example": "The soundtrack is unforgettable."},
        {"term": "Trailer", "translation": "short preview", "example": "The trailer gave it away."},
        {"term": "Blockbuster", "translation": "huge hit film", "example": "This summer blockbuster shattered records."},
        {"term": "Genre", "translation": "type of film", "example": "Horror is my favourite genre."},
        {"term": "Cliffhanger", "translation": "unresolved ending", "example": "That cliffhanger was cruel."},
    ],
    "fashion": [
        {"term": "Runway", "translation": "catwalk for fashion shows", "example": "The runway show sold out."},
        {"term": "Trend", "translation": "current popular style", "example": "That colour is on-trend."},
        {"term": "Wardrobe", "translation": "collection of clothes", "example": "A capsule wardrobe is simple."},
        {"term": "Silhouette", "translation": "outline of a garment", "example": "The silhouette is boxy."},
        {"term": "Tailored", "translation": "custom-fitted", "example": "The tailored blazer fits perfectly."},
        {"term": "Fabric", "translation": "cloth material", "example": "This fabric is soft."},
        {"term": "Designer", "translation": "clothes creator", "example": "A famous designer released the line."},
        {"term": "Palette", "translation": "colour range", "example": "The palette is muted."},
        {"term": "Accessory", "translation": "small style addition", "example": "A scarf is a nice accessory."},
        {"term": "Streetwear", "translation": "casual urban style", "example": "Streetwear defines the season."},
        {"term": "Vintage", "translation": "old-style clothing", "example": "This vintage dress is chic."},
        {"term": "Statement piece", "translation": "bold feature item", "example": "The coat is a statement piece."},
    ],
    "art": [
        {"term": "Composition", "translation": "arrangement of elements", "example": "The composition draws your eye."},
        {"term": "Palette", "translation": "chosen colours", "example": "She uses a warm palette."},
        {"term": "Brushstroke", "translation": "mark of a brush", "example": "Bold brushstrokes fill the canvas."},
        {"term": "Canvas", "translation": "painting surface", "example": "The canvas was primed."},
        {"term": "Sculpture", "translation": "3D artwork", "example": "The sculpture stood proudly."},
        {"term": "Portrait", "translation": "picture of a person", "example": "She painted a self-portrait."},
        {"term": "Landscape", "translation": "picture of scenery", "example": "The landscape captures autumn."},
        {"term": "Abstract", "translation": "non-representational", "example": "The abstract piece invites interpretation."},
        {"term": "Gallery", "translation": "space that shows art", "example": "The gallery opens tonight."},
        {"term": "Curator", "translation": "art selector", "example": "The curator arranged the show."},
        {"term": "Exhibit", "translation": "public art display", "example": "The exhibit runs all summer."},
        {"term": "Medium", "translation": "material used", "example": "Watercolour is her preferred medium."},
    ],
    "literature": [
        {"term": "Protagonist", "translation": "main character", "example": "The protagonist grows over time."},
        {"term": "Antagonist", "translation": "main opposing force", "example": "The antagonist is complex."},
        {"term": "Metaphor", "translation": "implied comparison", "example": "Time is a river — a metaphor."},
        {"term": "Simile", "translation": "compared with 'like/as'", "example": "Cold as ice — a simile."},
        {"term": "Narrator", "translation": "voice telling the story", "example": "The narrator is unreliable."},
        {"term": "Theme", "translation": "central idea", "example": "The theme is forgiveness."},
        {"term": "Prose", "translation": "ordinary writing", "example": "Her prose is elegant."},
        {"term": "Verse", "translation": "poetic form", "example": "Written in free verse."},
        {"term": "Genre", "translation": "type of writing", "example": "Fantasy is a fun genre."},
        {"term": "Foreshadow", "translation": "hint at what's coming", "example": "The opening foreshadows tragedy."},
        {"term": "Symbolism", "translation": "objects with deeper meaning", "example": "The river is heavy with symbolism."},
        {"term": "Manuscript", "translation": "unpublished draft", "example": "She sent the manuscript to publishers."},
    ],

    # ── Environment & society ─────────────────────────────────────────
    "environment": [
        {"term": "Sustainability", "translation": "meeting needs without harm", "example": "Sustainability drives design."},
        {"term": "Renewable", "translation": "endlessly replenished", "example": "Solar is renewable energy."},
        {"term": "Carbon footprint", "translation": "emissions caused", "example": "Reduce your carbon footprint."},
        {"term": "Biodiversity", "translation": "variety of life", "example": "Biodiversity is precious."},
        {"term": "Ecosystem", "translation": "living community + habitat", "example": "The ecosystem is fragile."},
        {"term": "Pollution", "translation": "harmful contamination", "example": "Pollution harms rivers."},
        {"term": "Recycle", "translation": "reuse material", "example": "Recycle your bottles."},
        {"term": "Emissions", "translation": "released gases", "example": "Emissions must drop."},
        {"term": "Habitat", "translation": "home of a species", "example": "Habitat loss is critical."},
        {"term": "Climate", "translation": "long-term weather", "example": "Climate is changing quickly."},
        {"term": "Deforestation", "translation": "clearing of forests", "example": "Deforestation harms species."},
        {"term": "Conservation", "translation": "protecting nature", "example": "Conservation efforts pay off."},
    ],
    "nature": [
        {"term": "Wildlife", "translation": "wild animals", "example": "The park protects wildlife."},
        {"term": "Predator", "translation": "hunter animal", "example": "Wolves are apex predators."},
        {"term": "Prey", "translation": "hunted animal", "example": "Rabbits are prey for owls."},
        {"term": "Migration", "translation": "seasonal movement", "example": "Bird migration begins in autumn."},
        {"term": "Species", "translation": "kind of organism", "example": "That species is rare."},
        {"term": "Canopy", "translation": "top layer of trees", "example": "Monkeys live in the canopy."},
        {"term": "Wilderness", "translation": "untouched land", "example": "We hiked into the wilderness."},
        {"term": "Terrain", "translation": "land features", "example": "The terrain is rocky."},
        {"term": "Climate zone", "translation": "region by weather", "example": "This is a tropical climate zone."},
        {"term": "Reserve", "translation": "protected area", "example": "The reserve shelters lions."},
        {"term": "Native", "translation": "naturally from a place", "example": "These plants are native."},
        {"term": "Endangered", "translation": "at risk of extinction", "example": "The species is endangered."},
    ],
    "space": [
        {"term": "Galaxy", "translation": "system of stars", "example": "Our galaxy is the Milky Way."},
        {"term": "Orbit", "translation": "path around a body", "example": "The satellite is in orbit."},
        {"term": "Constellation", "translation": "group of stars", "example": "Orion is a bright constellation."},
        {"term": "Nebula", "translation": "cloud of gas and dust", "example": "The nebula glowed in pink."},
        {"term": "Asteroid", "translation": "rocky object in space", "example": "The asteroid passed safely."},
        {"term": "Meteor", "translation": "space rock burning up", "example": "A meteor streaked the sky."},
        {"term": "Black hole", "translation": "region of intense gravity", "example": "Light cannot escape a black hole."},
        {"term": "Supernova", "translation": "exploding star", "example": "The supernova was visible."},
        {"term": "Solar system", "translation": "sun and its planets", "example": "Our solar system has eight planets."},
        {"term": "Light-year", "translation": "distance light travels in a year", "example": "That star is 4 light-years away."},
        {"term": "Cosmos", "translation": "the whole universe", "example": "The cosmos is vast."},
        {"term": "Astronaut", "translation": "space explorer", "example": "The astronaut waved."},
    ],
    "politics": [
        {"term": "Election", "translation": "vote to choose leaders", "example": "The election is next month."},
        {"term": "Constituent", "translation": "voter in a district", "example": "A constituent called the office."},
        {"term": "Legislation", "translation": "written laws", "example": "New legislation passed."},
        {"term": "Referendum", "translation": "public vote on an issue", "example": "The referendum was close."},
        {"term": "Bipartisan", "translation": "across two parties", "example": "The bill was bipartisan."},
        {"term": "Cabinet", "translation": "senior advisors", "example": "The cabinet met today."},
        {"term": "Diplomacy", "translation": "managing relations", "example": "Diplomacy prevents war."},
        {"term": "Sanction", "translation": "official penalty", "example": "New sanctions were announced."},
        {"term": "Amendment", "translation": "change to a law", "example": "The amendment passed."},
        {"term": "Filibuster", "translation": "long speech to delay", "example": "The filibuster took hours."},
        {"term": "Constitution", "translation": "founding law", "example": "The constitution guarantees rights."},
        {"term": "Ballot", "translation": "voting paper or process", "example": "Cast your ballot."},
    ],
    "psychology": [
        {"term": "Cognition", "translation": "mental processes", "example": "Cognition includes attention and memory."},
        {"term": "Behaviour", "translation": "observable action", "example": "Behaviour reveals motivation."},
        {"term": "Perception", "translation": "how we sense the world", "example": "Perception is not reality."},
        {"term": "Motivation", "translation": "drive to act", "example": "Intrinsic motivation is strongest."},
        {"term": "Bias", "translation": "systematic error", "example": "We all have biases."},
        {"term": "Reinforcement", "translation": "reward that increases behaviour", "example": "Positive reinforcement works."},
        {"term": "Habit", "translation": "automatic pattern", "example": "Small habits compound."},
        {"term": "Attachment", "translation": "emotional bond", "example": "Attachment develops early."},
        {"term": "Personality", "translation": "stable traits", "example": "She has a warm personality."},
        {"term": "Stress", "translation": "pressure response", "example": "Manage stress with sleep."},
        {"term": "Emotion", "translation": "feeling state", "example": "Emotion drives decisions."},
        {"term": "Introspection", "translation": "looking inward", "example": "Introspection builds insight."},
    ],
}


LESSONS_SEED: list[dict[str, Any]] = [
    # Healthcare
    {"id": "hc-job-interview", "title": "Prepare for a healthcare job interview", "description": "Common healthcare interview questions and tips on how to answer them.", "topic_id": "medicine", "level": "Advanced", "minutes": 35, "xp_reward": 40},
    {"id": "hc-cv", "title": "Writing a healthcare CV", "description": "Write a strong CV for a healthcare role. Learn vocabulary and structure.", "topic_id": "medicine", "level": "Intermediate", "minutes": 25, "xp_reward": 30},
    {"id": "hc-patient-history", "title": "Taking a patient history", "description": "Ask the right questions, in the right order, with the right tone.", "topic_id": "medicine", "level": "Advanced", "minutes": 30, "xp_reward": 35},
    {"id": "hc-empathy", "title": "Empathetic patient communication", "description": "Phrases that reassure and calm during difficult conversations.", "topic_id": "mental-health", "level": "Intermediate", "minutes": 20, "xp_reward": 25},
    {"id": "pharmacy-basics", "title": "Talking to patients in a pharmacy", "description": "Phrases and vocabulary used at the pharmacy counter.", "topic_id": "pharmacy", "level": "Beginner", "minutes": 20, "xp_reward": 20},
    {"id": "pharmacy-dosage", "title": "Explaining dosages clearly", "description": "How to describe timings, amounts, and warnings without ambiguity.", "topic_id": "pharmacy", "level": "Intermediate", "minutes": 22, "xp_reward": 25},
    {"id": "virology-terms", "title": "Essential virology vocabulary", "description": "Master core virology terms with real-world examples.", "topic_id": "virology", "level": "Advanced", "minutes": 30, "xp_reward": 35},
    {"id": "anatomy-body-systems", "title": "Talking about the body systems", "description": "Cardiac, pulmonary, renal — describe systems the way clinicians do.", "topic_id": "anatomy", "level": "Intermediate", "minutes": 25, "xp_reward": 30},
    {"id": "nursing-handover", "title": "Perfect the SBAR handover", "description": "Structure a clean, safe shift handover using SBAR.", "topic_id": "nursing", "level": "Intermediate", "minutes": 22, "xp_reward": 25},
    {"id": "mental-health-check-in", "title": "Well-being check-ins", "description": "Open, non-clinical questions that surface what really matters.", "topic_id": "mental-health", "level": "Beginner", "minutes": 15, "xp_reward": 20},

    # Academic & professional
    {"id": "business-emails", "title": "Writing professional emails", "description": "Craft clear, polite emails for meetings, follow-ups, and negotiations.", "topic_id": "business", "level": "Intermediate", "minutes": 22, "xp_reward": 25},
    {"id": "business-negotiation", "title": "Softening a negotiation", "description": "Push back with grace using calibrated language.", "topic_id": "business", "level": "Advanced", "minutes": 26, "xp_reward": 32},
    {"id": "business-standup", "title": "Nail your daily standup", "description": "Three lines that give a great status update every morning.", "topic_id": "business", "level": "Beginner", "minutes": 12, "xp_reward": 15},
    {"id": "finance-budgeting", "title": "Budgeting in plain English", "description": "Assets, liabilities, cash flow — explained simply.", "topic_id": "finance", "level": "Intermediate", "minutes": 24, "xp_reward": 28},
    {"id": "finance-market-news", "title": "Reading market news", "description": "Decode headlines about rates, yields, and volatility.", "topic_id": "finance", "level": "Advanced", "minutes": 26, "xp_reward": 30},
    {"id": "law-contract-basics", "title": "Contract basics", "description": "Parties, terms, obligations — read a simple contract with confidence.", "topic_id": "law", "level": "Intermediate", "minutes": 28, "xp_reward": 32},
    {"id": "tech-standup", "title": "Engineering standup phrases", "description": "Blocked, in review, shipping — talk shop with your team.", "topic_id": "tech", "level": "Beginner", "minutes": 15, "xp_reward": 18},
    {"id": "tech-code-review", "title": "Giving kind code review", "description": "Say what you mean without hurting feelings.", "topic_id": "tech", "level": "Intermediate", "minutes": 20, "xp_reward": 25},
    {"id": "marketing-copy", "title": "Writing landing-page copy", "description": "Hooks, benefits, proof — build a page that converts.", "topic_id": "marketing", "level": "Intermediate", "minutes": 22, "xp_reward": 28},
    {"id": "science-abstract", "title": "Reading a research abstract", "description": "Skim the parts that matter — hypothesis, method, result, conclusion.", "topic_id": "science", "level": "Advanced", "minutes": 24, "xp_reward": 30},
    {"id": "education-feedback", "title": "Giving useful feedback", "description": "Praise, correct, and coach with clear framing.", "topic_id": "education", "level": "Intermediate", "minutes": 20, "xp_reward": 25},

    # Lifestyle & culture
    {"id": "travel-airport", "title": "Airport English essentials", "description": "Check-in, security, boarding — travel with confidence.", "topic_id": "travel", "level": "Beginner", "minutes": 18, "xp_reward": 20},
    {"id": "travel-hotel", "title": "Checking in and out of a hotel", "description": "Reservations, requests, and polite complaints.", "topic_id": "travel", "level": "Beginner", "minutes": 15, "xp_reward": 18},
    {"id": "travel-restaurant", "title": "Ordering at a restaurant abroad", "description": "Menus, dietary needs, and paying gracefully.", "topic_id": "travel", "level": "Beginner", "minutes": 16, "xp_reward": 18},
    {"id": "cooking-recipe", "title": "Reading a recipe", "description": "Verbs that make you a better cook — simmer, sauté, fold.", "topic_id": "cooking", "level": "Beginner", "minutes": 18, "xp_reward": 20},
    {"id": "cooking-flavors", "title": "Describing flavour", "description": "Umami, tangy, mellow — talk about food like a critic.", "topic_id": "cooking", "level": "Intermediate", "minutes": 20, "xp_reward": 24},
    {"id": "sports-training", "title": "Talking about training", "description": "Warm-up, cool-down, personal best — sound like an athlete.", "topic_id": "sports", "level": "Beginner", "minutes": 15, "xp_reward": 18},
    {"id": "music-review", "title": "Writing a music review", "description": "Melody, tempo, mood — critique like a music journalist.", "topic_id": "music", "level": "Intermediate", "minutes": 22, "xp_reward": 26},
    {"id": "movies-critique", "title": "Discussing a film", "description": "Plot, cast, cinematography — build a rich film discussion.", "topic_id": "movies", "level": "Intermediate", "minutes": 22, "xp_reward": 26},
    {"id": "fashion-outfit", "title": "Describing an outfit", "description": "Silhouette, palette, tailoring — vocabulary that lands.", "topic_id": "fashion", "level": "Beginner", "minutes": 16, "xp_reward": 20},
    {"id": "art-gallery", "title": "Talking about art in a gallery", "description": "Explain what you feel and why using art vocabulary.", "topic_id": "art", "level": "Intermediate", "minutes": 22, "xp_reward": 25},
    {"id": "literature-essay", "title": "Writing a literary essay", "description": "Theme, metaphor, protagonist — structure a strong essay.", "topic_id": "literature", "level": "Advanced", "minutes": 28, "xp_reward": 34},

    # Environment & society
    {"id": "environment-climate", "title": "Discussing climate change", "description": "Carbon, emissions, renewables — talk about the challenge clearly.", "topic_id": "environment", "level": "Intermediate", "minutes": 24, "xp_reward": 28},
    {"id": "nature-hike", "title": "On a wildlife hike", "description": "Talk about terrain, species, and habitat while you walk.", "topic_id": "nature", "level": "Beginner", "minutes": 16, "xp_reward": 20},
    {"id": "space-astronomy", "title": "A tour of the night sky", "description": "Constellations, nebulas, orbits — beginner astronomy vocab.", "topic_id": "space", "level": "Intermediate", "minutes": 22, "xp_reward": 26},
    {"id": "politics-debate", "title": "Following a political debate", "description": "Legislation, referendum, amendment — decode the discussion.", "topic_id": "politics", "level": "Advanced", "minutes": 26, "xp_reward": 30},
    {"id": "psychology-habits", "title": "Talking about habits", "description": "Reinforcement, motivation, cue — the language of behaviour change.", "topic_id": "psychology", "level": "Intermediate", "minutes": 20, "xp_reward": 24},
]


CHALLENGES_SEED: list[dict[str, Any]] = [
    {"id": "learn-20-words", "title": "Learn 20 new words", "days_left": 3, "goal_type": "words_learned", "target": 20, "icon": "reader-outline"},
    {"id": "learn-50-words", "title": "Reach 50 words mastered", "days_left": 7, "goal_type": "words_learned", "target": 50, "icon": "library-outline"},
    {"id": "complete-3-lessons", "title": "Complete 3 lessons", "days_left": 5, "goal_type": "lessons_completed", "target": 3, "icon": "trophy-outline"},
    {"id": "complete-10-lessons", "title": "Finish 10 lessons this month", "days_left": 20, "goal_type": "lessons_completed", "target": 10, "icon": "medal-outline"},
    {"id": "3-day-streak", "title": "Reach a 3-day streak", "days_left": 7, "goal_type": "streak", "target": 3, "icon": "flame-outline"},
    {"id": "7-day-streak", "title": "Reach a 7-day streak", "days_left": 14, "goal_type": "streak", "target": 7, "icon": "flame"},
    {"id": "30-day-streak", "title": "Reach a 30-day streak", "days_left": 45, "goal_type": "streak", "target": 30, "icon": "sparkles-outline"},
]
